// src/lib/i18n.js
import { useState, useEffect, useCallback } from "react";

export const LANGUAGES = [
  { code: "sq", label: "Shqip",    flag: "🇦🇱" },
  { code: "en", label: "English",  flag: "🇬🇧" },
  { code: "it", label: "Italiano", flag: "🇮🇹" },
  { code: "de", label: "Deutsch",  flag: "🇩🇪" },
  { code: "el", label: "Ελληνικά", flag: "🇬🇷" },
  { code: "tr", label: "Türkçe",   flag: "🇹🇷" },
  { code: "fr", label: "Français", flag: "🇫🇷" },
];

const sq = {
  nav: { home:"Kryefaqja", services:"Shërbimet", showroom:"Showroom", products:"Produktet", solar:"Solar", blog:"Blog", contact:"Kontakt", cta:"Kërko Ofertë" },
  hero: { badge:"Që nga viti 1990", title:"Sepse çdo shtëpi", titleEm:"meriton të duket si ëndërr", subtitle:"36 vjet përvojë në rinovim banjash, panele diellore dhe shitje produktesh cilësore.", cta1:"Shiko Showroom", cta2:"Kontakto Tani", stat1:"Vite Përvojë", stat2:"Projekte", stat3:"Gjithë Evropën" },
  services: { label:"Shërbimet Tona", title1:"Çfarë", titleEm:"ofrojmë", subtitle:"Zgjidhje të plota për shtëpinë tuaj.", s1t:"Rinovim Banje", s1d:"Rinovim i plotë i banjës nga projektimi deri te montimi.", s2t:"Konsultim Falas", s2d:"Konsultim falas dhe projekt 3D për hapësirën tuaj.", s3t:"Panele Diellore", s3d:"Instalim panelesh për shtëpi, biznes dhe tokë bujqësore.", s4t:"Shitje Produktesh", s4d:"Pllaka, hidrosanitare, mobilje dhe ndriçim me dorëzim në Evropë.", link:"Mëso më shumë" },
  showroom: { label:"Showroom", title1:"Vizitoni showroom-in tonë në", titleEm:"Belsh", subtitle:"Ekspozitë me mbi 50 ambiente të mobiluara.", cta:"Na Vizitoni" },
  products: { label:"Produktet", title1:"Shfleto sipas", titleEm:"kategorisë", subtitle:"Gama e gjerë produktesh cilësore.", c1:"Pllaka", c1d:"Dysheme & Mure", c2:"Hidrosanitare", c2d:"Rubineta & Dushe", c3:"Mobilje Banje", c3d:"Vanitet & Pasqyra", c4:"Ndriçim", c4d:"LED & Dekorativ", c5:"Kuzhinë", c5d:"Lavamane & Aksesore", c6:"Aksesore", c6d:"Mbajtëse & Detaje", viewAll:"Shiko të gjitha", filter:"Filtro:", filterAll:"Të gjitha", filterBath:"Banjë", filterKitchen:"Kuzhinë", filterLiving:"Dhomë ndenjeje", newBadge:"E Re" },
  transform: { label:"Transformo Banjën", title1:"Dërgoni foton, ne e bëjmë", titleEm:"realitet", subtitle:"Ngarkoni deri në 5 foto të banjës dhe përshkruani vizionin tuaj.", name:"Emri i Plotë", phone:"Numri i Telefonit", email:"Email (opsional)", vision:"Përshkruani vizionin tuaj", upload:"Klikoni për të ngarkuar foto ose tërhiqni këtu", uploadHint:"Deri në 5 foto · JPG, PNG, WEBP", send:"Dërgo Kërkesën", beforeAfter:"Para & Pas", baDesc:"Shihni si i transformojmë hapësirat", count:"foto të ngarkuara", thanks:"Faleminderit!", thanksMsg:"Kërkesa u dërgua. Do t'ju kontaktojmë brenda 24 orëve.", errReq:"Plotësoni fushat e detyruara.", errMax:"Maksimumi 5 foto.", errType:"Vetëm imazhe (JPG, PNG, WEBP)." },
  solar: { label:"Energjia Diellore", title1:"Panele diellore për një", titleEm:"të ardhme më të mirë", desc:"Dervishi Group ofron instalim të plotë të paneleve diellore. Kurseni deri në 80% të faturës.", f1:"Rezidenciale", f1d:"Për shtëpi & apartamente", f2:"Komerciale", f2d:"Për biznese & hotele", f3:"Bujqësore", f3d:"Për toka & ferma", f4:"Instalim i Plotë", f4d:"Nga projekti deri te montimi", calcTitle:"Kalkulator Solar", calcSub:"Zbuloni sa mund të kurseni", billLabel:"Fatura mujore e energjisë", currency:"Monedha", calculate:"Llogarit Kursimet", annualSave:"Kursime Vjetore", kwh:"kWh / Vit", panels:"Panele", payback:"Vite Kthimi", cta:"Merr Ofertë Solar" },
  blog: { label:"Blog", title1:"Artikuj dhe", titleEm:"këshilla", subtitle:"Lexoni artikujt tanë mbi rinovime, trende dhe këshilla.", read:"Lexo më shumë", empty:"Asnjë artikull i publikuar ende." },
  testimonials: { label:"Klientët Tanë", title1:"Çfarë thonë", titleEm:"klientët", subtitle:"Rishikime nga klientë realë.", empty:"Së shpejti..." },
  consultation: { label:"Konsultim Falas", title1:"Rezervoni një", titleEm:"konsultim", subtitle:"Konsultim falas — vizitë në vend ose në showroom.", name:"Emri", phone:"Telefoni", date:"Data e preferuar", message:"Mesazhi", book:"Rezervo", success:"Rezervimi u dërgua!" },
  contact: { label:"Na Kontaktoni", title1:"Gati për të nisur", titleEm:"projektin tuaj?", subtitle:"Konsultim FALAS — na kontaktoni sot.", address:"Rruga 31 Gushti, Belsh", hours:"Hënë – Shtunë, 07:00 – 18:00", name:"Emri", email:"Email", phone:"Telefoni", message:"Mesazhi", send:"Dërgo Mesazhin", info:"Informacioni", whatsapp:"WhatsApp", directions:"Drejtimet", success:"Mesazhi u dërgua me sukses!" },
  faq: { label:"FAQ", title1:"Pyetjet e", titleEm:"shpeshta", q1:"A bëni dorëzim jashtë Shqipërisë?", a1:"Po, dorëzojmë në të gjithë Evropën — Kosovë, Maqedoni e Veriut, Itali, Gjermani etj.", q2:"Sa zgjat një rinovim banje?", a2:"Çdo projekt është i ndryshëm. Mesatarisht 3-6 javë. Na kontaktoni për një vlerësim.", q3:"A është vërtet falas konsultimi?", a3:"Po, konsultimi i parë dhe projekti 3D janë plotësisht falas.", q4:"Çfarë markash punoni?", a4:"Punojmë me markat më të mira evropiane për pllaka, hidrosanitare dhe mobilje banje." },
  footer: { tagline:"Sepse çdo shtëpi meriton të duket si ëndërr.", services:"Shërbimet", company:"Kompania", contactCol:"Kontakt", about:"Rreth Nesh", projects:"Projektet", admin:"Admin", rights:"Të gjitha të drejtat e rezervuara." },
  admin: { login:"Hyr", loginTitle:"Panel Administrimi", email:"Email", password:"Fjalëkalimi", back:"Kthehu në Faqe", err:"Email ose fjalëkalim i gabuar.", logout:"Dil", role:"admin", today:"Sot", dashboard:"Paneli", quotes:"Kërkesat për Ofertë", transforms:"Transformime", products:"Produkte", blog:"Blog", projects:"Projekte / Portfolio", solar:"Konfigurim Solar", testimonials:"Testimoniale", consultations:"Konsultime", settings:"Cilësimet", search:"Kërko...", export:"Eksporto CSV", add:"Shto", edit:"Modifiko", delete:"Fshi", save:"Ruaj", cancel:"Anulo", confirm:"Konfirmo", confirmDelete:"Jeni i sigurt që doni ta fshini?", date:"Data", name:"Emri", phone:"Telefoni", message:"Mesazhi", status:"Statusi", actions:"Veprime", empty:"Asnjë e dhënë ende.", saved:"U ruajt!", deleted:"U fshi!", statusNew:"E re", statusProgress:"Në proces", statusDone:"Përfunduar", statusSent:"Dërguar propozimi", statusConfirmed:"Konfirmuar", statusCancelled:"Anuluar", title:"Titulli", category:"Kategoria", description:"Përshkrimi", brand:"Marka", image:"Imazhi", featured:"E veçantë", published:"Publikuar", draft:"Draft", stars:"Yje", review:"Rishikimi", location:"Vendndodhja", duration:"Kohëzgjatja", before:"Foto Para", after:"Foto Pas", company:"Kompania", logo:"Logo", lastUpdated:"Përditësuar më", reset:"Rikthe parazgjedhjet" }
};

// English
const en = {
  nav: { home:"Home", services:"Services", showroom:"Showroom", products:"Products", solar:"Solar", blog:"Blog", contact:"Contact", cta:"Get Quote" },
  hero: { badge:"Since 1990", title:"Because every home", titleEm:"deserves to look like a dream", subtitle:"36 years of experience in bathroom renovation, solar panels and quality product sales.", cta1:"View Showroom", cta2:"Contact Us", stat1:"Years Experience", stat2:"Projects", stat3:"All of Europe" },
  services: { label:"Our Services", title1:"What we", titleEm:"offer", subtitle:"Complete solutions for your home.", s1t:"Bathroom Renovation", s1d:"Full bathroom renovation from design to installation.", s2t:"Free Consultation", s2d:"Free consultation and 3D project for your space.", s3t:"Solar Panels", s3d:"Panel installation for homes, businesses and farmland.", s4t:"Product Sales", s4d:"Tiles, fixtures, furniture and lighting with delivery across Europe.", link:"Learn more" },
  showroom: { label:"Showroom", title1:"Visit our showroom in", titleEm:"Belsh", subtitle:"Exhibition with over 50 furnished environments.", cta:"Visit Us" },
  products: { label:"Products", title1:"Browse by", titleEm:"category", subtitle:"Wide range of quality products.", c1:"Tiles", c1d:"Floor & Wall", c2:"Hydrosanitary", c2d:"Faucets & Showers", c3:"Bathroom Furniture", c3d:"Vanities & Mirrors", c4:"Lighting", c4d:"LED & Decorative", c5:"Kitchen", c5d:"Sinks & Accessories", c6:"Accessories", c6d:"Holders & Details", viewAll:"View All", filter:"Filter:", filterAll:"All", filterBath:"Bathroom", filterKitchen:"Kitchen", filterLiving:"Living Room", newBadge:"New" },
  transform: { label:"Transform Your Bathroom", title1:"Send your photo, we make it", titleEm:"reality", subtitle:"Upload up to 5 photos and describe your vision.", name:"Full Name", phone:"Phone Number", email:"Email (optional)", vision:"Describe your vision", upload:"Click to upload or drag photos here", uploadHint:"Up to 5 photos · JPG, PNG, WEBP", send:"Send Request", beforeAfter:"Before & After", baDesc:"See how we transform spaces", count:"photos uploaded", thanks:"Thank you!", thanksMsg:"Request received. We'll contact you within 24 hours.", errReq:"Please fill required fields.", errMax:"Maximum 5 photos.", errType:"Images only (JPG, PNG, WEBP)." },
  solar: { label:"Solar Energy", title1:"Solar panels for a", titleEm:"better future", desc:"Dervishi Group offers complete solar panel installation. Save up to 80% on your bill.", f1:"Residential", f1d:"For homes & apartments", f2:"Commercial", f2d:"For businesses & hotels", f3:"Agricultural", f3d:"For land & farms", f4:"Full Installation", f4d:"From project to mounting", calcTitle:"Solar Calculator", calcSub:"Discover how much you can save", billLabel:"Monthly electricity bill", currency:"Currency", calculate:"Calculate Savings", annualSave:"Annual Savings", kwh:"kWh / Year", panels:"Panels", payback:"Payback Years", cta:"Get Solar Quote" },
  blog: { label:"Blog", title1:"Articles and", titleEm:"tips", subtitle:"Read our articles on renovations, trends and tips.", read:"Read More", empty:"No articles published yet." },
  testimonials: { label:"Our Clients", title1:"What clients", titleEm:"say", subtitle:"Reviews from real clients.", empty:"Coming soon..." },
  consultation: { label:"Free Consultation", title1:"Book a", titleEm:"consultation", subtitle:"Free consultation — site visit or showroom.", name:"Name", phone:"Phone", date:"Preferred date", message:"Message", book:"Book", success:"Booking sent!" },
  contact: { label:"Contact Us", title1:"Ready to start", titleEm:"your project?", subtitle:"FREE consultation — contact us today.", address:"Rruga 31 Gushti, Belsh", hours:"Mon – Sat, 07:00 – 18:00", name:"Name", email:"Email", phone:"Phone", message:"Message", send:"Send Message", info:"Information", whatsapp:"WhatsApp", directions:"Directions", success:"Message sent successfully!" },
  faq: { label:"FAQ", title1:"Frequently Asked", titleEm:"Questions", q1:"Do you deliver outside Albania?", a1:"Yes, we deliver across Europe — Kosovo, North Macedonia, Italy, Germany etc.", q2:"How long does a bathroom renovation take?", a2:"Every project is different. Average 3-6 weeks. Contact us for an estimate.", q3:"Is the consultation really free?", a3:"Yes, the first consultation and 3D project are completely free.", q4:"What brands do you carry?", a4:"We work with the best European brands for tiles, fixtures and bathroom furniture." },
  footer: { tagline:"Because every home deserves to look like a dream.", services:"Services", company:"Company", contactCol:"Contact", about:"About Us", projects:"Projects", admin:"Admin", rights:"All rights reserved." },
  admin: { login:"Login", loginTitle:"Admin Panel", email:"Email", password:"Password", back:"Back to Site", err:"Wrong email or password.", logout:"Logout", role:"admin", today:"Today", dashboard:"Dashboard", quotes:"Quote Requests", transforms:"Transforms", products:"Products", blog:"Blog", projects:"Projects / Portfolio", solar:"Solar Config", testimonials:"Testimonials", consultations:"Consultations", settings:"Settings", search:"Search...", export:"Export CSV", add:"Add", edit:"Edit", delete:"Delete", save:"Save", cancel:"Cancel", confirm:"Confirm", confirmDelete:"Are you sure you want to delete?", date:"Date", name:"Name", phone:"Phone", message:"Message", status:"Status", actions:"Actions", empty:"No data yet.", saved:"Saved!", deleted:"Deleted!", statusNew:"New", statusProgress:"In Progress", statusDone:"Completed", statusSent:"Proposal Sent", statusConfirmed:"Confirmed", statusCancelled:"Cancelled", title:"Title", category:"Category", description:"Description", brand:"Brand", image:"Image", featured:"Featured", published:"Published", draft:"Draft", stars:"Stars", review:"Review", location:"Location", duration:"Duration", before:"Before Photo", after:"After Photo", company:"Company", logo:"Logo", lastUpdated:"Last updated", reset:"Reset to defaults" }
};

// Italian
const it = {
  nav: { home:"Home", services:"Servizi", showroom:"Showroom", products:"Prodotti", solar:"Solare", blog:"Blog", contact:"Contatti", cta:"Preventivo" },
  hero: { badge:"Dal 1990", title:"Perché ogni casa", titleEm:"merita di sembrare un sogno", subtitle:"36 anni di esperienza in ristrutturazioni bagno, pannelli solari e vendita prodotti di qualità.", cta1:"Vedi Showroom", cta2:"Contattaci", stat1:"Anni di Esperienza", stat2:"Progetti", stat3:"Tutta l'Europa" },
  services: { label:"I Nostri Servizi", title1:"Cosa", titleEm:"offriamo", subtitle:"Soluzioni complete per la tua casa.", s1t:"Ristrutturazione Bagno", s1d:"Ristrutturazione completa dal progetto al montaggio.", s2t:"Consulenza Gratuita", s2d:"Consulenza gratuita e progetto 3D.", s3t:"Pannelli Solari", s3d:"Installazione per case, aziende e terreni agricoli.", s4t:"Vendita Prodotti", s4d:"Piastrelle, sanitari, mobili con consegna in Europa.", link:"Scopri di più" },
  showroom: { label:"Showroom", title1:"Visita il nostro showroom a", titleEm:"Belsh", subtitle:"Esposizione con oltre 50 ambienti arredati.", cta:"Visitaci" },
  products: { label:"Prodotti", title1:"Sfoglia per", titleEm:"categoria", subtitle:"Ampia gamma di prodotti di qualità.", c1:"Piastrelle", c1d:"Pavimento & Parete", c2:"Sanitari", c2d:"Rubinetti & Docce", c3:"Mobili Bagno", c3d:"Mobili & Specchi", c4:"Illuminazione", c4d:"LED & Decorativo", c5:"Cucina", c5d:"Lavelli & Accessori", c6:"Accessori", c6d:"Supporti & Dettagli", viewAll:"Vedi tutti", filter:"Filtra:", filterAll:"Tutti", filterBath:"Bagno", filterKitchen:"Cucina", filterLiving:"Soggiorno", newBadge:"Novità" },
  transform: { label:"Trasforma il Tuo Bagno", title1:"Manda la foto, la rendiamo", titleEm:"realtà", subtitle:"Carica fino a 5 foto e descrivi la tua visione.", name:"Nome Completo", phone:"Telefono", email:"Email (opzionale)", vision:"Descrivi la tua visione", upload:"Clicca per caricare le foto", uploadHint:"Fino a 5 foto · JPG, PNG, WEBP", send:"Invia Richiesta", beforeAfter:"Prima & Dopo", baDesc:"Guarda come trasformiamo gli spazi", count:"foto caricate", thanks:"Grazie!", thanksMsg:"Richiesta ricevuta. Ti contatteremo entro 24 ore.", errReq:"Compila i campi obbligatori.", errMax:"Massimo 5 foto.", errType:"Solo immagini (JPG, PNG, WEBP)." },
  solar: { label:"Energia Solare", title1:"Pannelli solari per un", titleEm:"futuro migliore", desc:"Dervishi Group offre installazione completa di pannelli solari. Risparmia fino all'80% sulla bolletta.", f1:"Residenziale", f1d:"Per case & appartamenti", f2:"Commerciale", f2d:"Per aziende & hotel", f3:"Agricolo", f3d:"Per terreni & fattorie", f4:"Installazione Completa", f4d:"Dal progetto al montaggio", calcTitle:"Calcolatore Solare", calcSub:"Scopri quanto puoi risparmiare", billLabel:"Bolletta mensile", currency:"Valuta", calculate:"Calcola Risparmi", annualSave:"Risparmi Annuali", kwh:"kWh / Anno", panels:"Pannelli", payback:"Anni Rientro", cta:"Richiedi Preventivo" },
  blog: { label:"Blog", title1:"Articoli e", titleEm:"consigli", subtitle:"Leggi i nostri articoli su ristrutturazioni e trend.", read:"Leggi di più", empty:"Nessun articolo ancora pubblicato." },
  testimonials: { label:"I Nostri Clienti", title1:"Cosa dicono i", titleEm:"clienti", subtitle:"Recensioni da clienti reali.", empty:"Prossimamente..." },
  consultation: { label:"Consulenza Gratuita", title1:"Prenota una", titleEm:"consulenza", subtitle:"Consulenza gratuita — sopralluogo o showroom.", name:"Nome", phone:"Telefono", date:"Data preferita", message:"Messaggio", book:"Prenota", success:"Prenotazione inviata!" },
  contact: { label:"Contattaci", title1:"Pronto a iniziare", titleEm:"il tuo progetto?", subtitle:"Consulenza GRATUITA — contattaci oggi.", address:"Rruga 31 Gushti, Belsh", hours:"Lun – Sab, 07:00 – 18:00", name:"Nome", email:"Email", phone:"Telefono", message:"Messaggio", send:"Invia Messaggio", info:"Informazioni", whatsapp:"WhatsApp", directions:"Indicazioni", success:"Messaggio inviato!" },
  faq: { label:"FAQ", title1:"Domande", titleEm:"frequenti", q1:"Consegnate fuori dall'Albania?", a1:"Sì, consegniamo in tutta Europa — Kosovo, Macedonia, Italia, Germania ecc.", q2:"Quanto dura una ristrutturazione?", a2:"Ogni progetto è diverso. Media 3-6 settimane.", q3:"La consulenza è davvero gratuita?", a3:"Sì, la prima consulenza e il progetto 3D sono completamente gratuiti.", q4:"Con quali marchi lavorate?", a4:"Lavoriamo con i migliori marchi europei per piastrelle, sanitari e mobili." },
  footer: { tagline:"Perché ogni casa merita di sembrare un sogno.", services:"Servizi", company:"Azienda", contactCol:"Contatti", about:"Chi Siamo", projects:"Progetti", admin:"Admin", rights:"Tutti i diritti riservati." },
  admin: { login:"Accedi", loginTitle:"Pannello Admin", email:"Email", password:"Password", back:"Torna al Sito", err:"Email o password errati.", logout:"Esci", role:"admin", today:"Oggi", dashboard:"Dashboard", quotes:"Richieste Preventivo", transforms:"Trasformazioni", products:"Prodotti", blog:"Blog", projects:"Progetti / Portfolio", solar:"Config. Solare", testimonials:"Testimonianze", consultations:"Consulenze", settings:"Impostazioni", search:"Cerca...", export:"Esporta CSV", add:"Aggiungi", edit:"Modifica", delete:"Elimina", save:"Salva", cancel:"Annulla", confirm:"Conferma", confirmDelete:"Sei sicuro di voler eliminare?", date:"Data", name:"Nome", phone:"Telefono", message:"Messaggio", status:"Stato", actions:"Azioni", empty:"Nessun dato.", saved:"Salvato!", deleted:"Eliminato!", statusNew:"Nuovo", statusProgress:"In Corso", statusDone:"Completato", statusSent:"Proposta Inviata", statusConfirmed:"Confermato", statusCancelled:"Annullato", title:"Titolo", category:"Categoria", description:"Descrizione", brand:"Marca", image:"Immagine", featured:"In evidenza", published:"Pubblicato", draft:"Bozza", stars:"Stelle", review:"Recensione", location:"Località", duration:"Durata", before:"Foto Prima", after:"Foto Dopo", company:"Azienda", logo:"Logo", lastUpdated:"Aggiornato il", reset:"Ripristina" }
};

// German
const de = {
  nav: { home:"Start", services:"Leistungen", showroom:"Showroom", products:"Produkte", solar:"Solar", blog:"Blog", contact:"Kontakt", cta:"Angebot" },
  hero: { badge:"Seit 1990", title:"Weil jedes Zuhause", titleEm:"wie ein Traum aussehen sollte", subtitle:"36 Jahre Erfahrung in Badrenovierung, Solaranlagen und Qualitätsprodukten.", cta1:"Showroom ansehen", cta2:"Kontaktieren", stat1:"Jahre Erfahrung", stat2:"Projekte", stat3:"Ganz Europa" },
  services: { label:"Unsere Leistungen", title1:"Was wir", titleEm:"anbieten", subtitle:"Komplettlösungen für Ihr Zuhause.", s1t:"Badrenovierung", s1d:"Komplette Badrenovierung von Planung bis Montage.", s2t:"Kostenlose Beratung", s2d:"Kostenlose Beratung und 3D-Projekt.", s3t:"Solaranlagen", s3d:"Installation für Häuser, Unternehmen und Agrarflächen.", s4t:"Produktverkauf", s4d:"Fliesen, Sanitär, Möbel mit Lieferung in Europa.", link:"Mehr erfahren" },
  showroom: { label:"Showroom", title1:"Besuchen Sie unseren Showroom in", titleEm:"Belsh", subtitle:"Ausstellung mit über 50 eingerichteten Räumen.", cta:"Besuchen Sie uns" },
  products: { label:"Produkte", title1:"Stöbern nach", titleEm:"Kategorie", subtitle:"Breites Sortiment an Qualitätsprodukten.", c1:"Fliesen", c1d:"Boden & Wand", c2:"Sanitär", c2d:"Armaturen & Duschen", c3:"Badmöbel", c3d:"Waschtische & Spiegel", c4:"Beleuchtung", c4d:"LED & Dekorativ", c5:"Küche", c5d:"Spülen & Zubehör", c6:"Zubehör", c6d:"Halterungen & Details", viewAll:"Alle anzeigen", filter:"Filter:", filterAll:"Alle", filterBath:"Bad", filterKitchen:"Küche", filterLiving:"Wohnzimmer", newBadge:"Neu" },
  transform: { label:"Bad Verwandeln", title1:"Schicken Sie das Foto, wir machen es", titleEm:"Realität", subtitle:"Laden Sie bis zu 5 Fotos hoch und beschreiben Sie Ihre Vision.", name:"Vollständiger Name", phone:"Telefon", email:"E-Mail (optional)", vision:"Beschreiben Sie Ihre Vision", upload:"Klicken zum Hochladen", uploadHint:"Bis zu 5 Fotos · JPG, PNG, WEBP", send:"Anfrage senden", beforeAfter:"Vorher & Nachher", baDesc:"So verwandeln wir Räume", count:"Fotos hochgeladen", thanks:"Danke!", thanksMsg:"Anfrage erhalten. Wir melden uns innerhalb von 24 Stunden.", errReq:"Pflichtfelder ausfüllen.", errMax:"Maximal 5 Fotos.", errType:"Nur Bilder (JPG, PNG, WEBP)." },
  solar: { label:"Solarenergie", title1:"Solarpanels für eine", titleEm:"bessere Zukunft", desc:"Dervishi Group bietet komplette Solaranlagen. Sparen Sie bis zu 80% Ihrer Stromrechnung.", f1:"Wohnbau", f1d:"Für Häuser & Wohnungen", f2:"Gewerbe", f2d:"Für Unternehmen & Hotels", f3:"Landwirtschaft", f3d:"Für Land & Höfe", f4:"Komplettinstallation", f4d:"Vom Projekt bis zur Montage", calcTitle:"Solar-Rechner", calcSub:"Entdecken Sie Ihr Sparpotenzial", billLabel:"Monatliche Stromrechnung", currency:"Währung", calculate:"Ersparnis berechnen", annualSave:"Jährliche Ersparnis", kwh:"kWh / Jahr", panels:"Module", payback:"Amortisation Jahre", cta:"Solar-Angebot" },
  blog: { label:"Blog", title1:"Artikel und", titleEm:"Tipps", subtitle:"Lesen Sie unsere Artikel zu Renovierung und Trends.", read:"Mehr lesen", empty:"Noch keine Artikel veröffentlicht." },
  testimonials: { label:"Unsere Kunden", title1:"Was Kunden", titleEm:"sagen", subtitle:"Bewertungen von echten Kunden.", empty:"Bald verfügbar..." },
  consultation: { label:"Kostenlose Beratung", title1:"Buchen Sie eine", titleEm:"Beratung", subtitle:"Kostenlose Beratung — vor Ort oder im Showroom.", name:"Name", phone:"Telefon", date:"Wunschtermin", message:"Nachricht", book:"Buchen", success:"Buchung gesendet!" },
  contact: { label:"Kontakt", title1:"Bereit, Ihr", titleEm:"Projekt zu starten?", subtitle:"KOSTENLOSE Beratung — kontaktieren Sie uns heute.", address:"Rruga 31 Gushti, Belsh", hours:"Mo – Sa, 07:00 – 18:00", name:"Name", email:"E-Mail", phone:"Telefon", message:"Nachricht", send:"Nachricht senden", info:"Information", whatsapp:"WhatsApp", directions:"Wegbeschreibung", success:"Nachricht erfolgreich gesendet!" },
  faq: { label:"FAQ", title1:"Häufig gestellte", titleEm:"Fragen", q1:"Liefern Sie auch außerhalb Albaniens?", a1:"Ja, wir liefern in ganz Europa — Kosovo, Nordmazedonien, Italien, Deutschland usw.", q2:"Wie lange dauert eine Badrenovierung?", a2:"Jedes Projekt ist anders. Durchschnittlich 3-6 Wochen.", q3:"Ist die Beratung wirklich kostenlos?", a3:"Ja, die Erstberatung und das 3D-Projekt sind völlig kostenlos.", q4:"Mit welchen Marken arbeiten Sie?", a4:"Wir arbeiten mit den besten europäischen Marken." },
  footer: { tagline:"Weil jedes Zuhause wie ein Traum aussehen sollte.", services:"Leistungen", company:"Unternehmen", contactCol:"Kontakt", about:"Über uns", projects:"Projekte", admin:"Admin", rights:"Alle Rechte vorbehalten." },
  admin: { login:"Anmelden", loginTitle:"Admin-Panel", email:"E-Mail", password:"Passwort", back:"Zurück", err:"Falsche E-Mail oder Passwort.", logout:"Abmelden", role:"Admin", today:"Heute", dashboard:"Dashboard", quotes:"Angebotsanfragen", transforms:"Verwandlungen", products:"Produkte", blog:"Blog", projects:"Projekte", solar:"Solar-Konfig.", testimonials:"Bewertungen", consultations:"Beratungen", settings:"Einstellungen", search:"Suchen...", export:"CSV exportieren", add:"Hinzufügen", edit:"Bearbeiten", delete:"Löschen", save:"Speichern", cancel:"Abbrechen", confirm:"Bestätigen", confirmDelete:"Wirklich löschen?", date:"Datum", name:"Name", phone:"Telefon", message:"Nachricht", status:"Status", actions:"Aktionen", empty:"Keine Daten.", saved:"Gespeichert!", deleted:"Gelöscht!", statusNew:"Neu", statusProgress:"In Bearbeitung", statusDone:"Abgeschlossen", statusSent:"Vorschlag gesendet", statusConfirmed:"Bestätigt", statusCancelled:"Storniert", title:"Titel", category:"Kategorie", description:"Beschreibung", brand:"Marke", image:"Bild", featured:"Hervorgehoben", published:"Veröffentlicht", draft:"Entwurf", stars:"Sterne", review:"Bewertung", location:"Ort", duration:"Dauer", before:"Vorher-Foto", after:"Nachher-Foto", company:"Firma", logo:"Logo", lastUpdated:"Aktualisiert", reset:"Zurücksetzen" }
};

// Greek
const el = {
  nav: { home:"Αρχική", services:"Υπηρεσίες", showroom:"Έκθεση", products:"Προϊόντα", solar:"Φωτοβολταϊκά", blog:"Blog", contact:"Επικοινωνία", cta:"Προσφορά" },
  hero: { badge:"Από το 1990", title:"Γιατί κάθε σπίτι", titleEm:"αξίζει να μοιάζει με όνειρο", subtitle:"36 χρόνια εμπειρίας σε ανακαίνιση μπάνιου, φωτοβολταϊκά και προϊόντα ποιότητας.", cta1:"Δείτε την Έκθεση", cta2:"Επικοινωνία", stat1:"Χρόνια Εμπειρίας", stat2:"Έργα", stat3:"Όλη την Ευρώπη" },
  services: { label:"Οι Υπηρεσίες μας", title1:"Τι", titleEm:"προσφέρουμε", subtitle:"Ολοκληρωμένες λύσεις για το σπίτι σας.", s1t:"Ανακαίνιση Μπάνιου", s1d:"Πλήρης ανακαίνιση από σχεδιασμό μέχρι τοποθέτηση.", s2t:"Δωρεάν Συμβουλευτική", s2d:"Δωρεάν συμβουλευτική και 3D σχέδιο.", s3t:"Φωτοβολταϊκά", s3d:"Εγκατάσταση σε σπίτια, επιχειρήσεις και αγροκτήματα.", s4t:"Πωλήσεις Προϊόντων", s4d:"Πλακάκια, είδη υγιεινής, έπιπλα με παράδοση στην Ευρώπη.", link:"Μάθε περισσότερα" },
  showroom: { label:"Έκθεση", title1:"Επισκεφθείτε την έκθεσή μας στο", titleEm:"Belsh", subtitle:"Έκθεση με πάνω από 50 διαμορφωμένους χώρους.", cta:"Επισκεφθείτε μας" },
  products: { label:"Προϊόντα", title1:"Αναζήτηση κατά", titleEm:"κατηγορία", subtitle:"Ευρεία γκάμα προϊόντων ποιότητας.", c1:"Πλακάκια", c1d:"Δάπεδο & Τοίχου", c2:"Είδη Υγιεινής", c2d:"Βρύσες & Ντους", c3:"Έπιπλα Μπάνιου", c3d:"Νιπτήρες & Καθρέφτες", c4:"Φωτισμός", c4d:"LED & Διακοσμητικός", c5:"Κουζίνα", c5d:"Νεροχύτες & Αξεσουάρ", c6:"Αξεσουάρ", c6d:"Στηρίγματα & Λεπτομέρειες", viewAll:"Δείτε όλα", filter:"Φίλτρο:", filterAll:"Όλα", filterBath:"Μπάνιο", filterKitchen:"Κουζίνα", filterLiving:"Σαλόνι", newBadge:"Νέο" },
  transform: { label:"Μεταμορφώστε το Μπάνιο", title1:"Στείλτε φωτογραφία, το κάνουμε", titleEm:"πραγματικότητα", subtitle:"Ανεβάστε έως 5 φωτογραφίες και περιγράψτε το όραμά σας.", name:"Πλήρες Όνομα", phone:"Τηλέφωνο", email:"Email (προαιρετικό)", vision:"Περιγράψτε το όραμά σας", upload:"Κάντε κλικ για ανέβασμα", uploadHint:"Έως 5 φωτογραφίες · JPG, PNG, WEBP", send:"Αποστολή", beforeAfter:"Πριν & Μετά", baDesc:"Δείτε πώς μεταμορφώνουμε χώρους", count:"φωτογραφίες ανεβάστηκαν", thanks:"Ευχαριστούμε!", thanksMsg:"Το αίτημα ελήφθη. Θα επικοινωνήσουμε εντός 24 ωρών.", errReq:"Συμπληρώστε τα υποχρεωτικά πεδία.", errMax:"Μέγιστο 5 φωτογραφίες.", errType:"Μόνο εικόνες (JPG, PNG, WEBP)." },
  solar: { label:"Ηλιακή Ενέργεια", title1:"Φωτοβολταϊκά για ένα", titleEm:"καλύτερο μέλλον", desc:"Η Dervishi Group προσφέρει πλήρη εγκατάσταση φωτοβολταϊκών. Εξοικονομήστε έως 80%.", f1:"Οικιστικά", f1d:"Για σπίτια & διαμερίσματα", f2:"Εμπορικά", f2d:"Για επιχειρήσεις & ξενοδοχεία", f3:"Αγροτικά", f3d:"Για γη & αγροκτήματα", f4:"Πλήρης Εγκατάσταση", f4d:"Από το έργο στην τοποθέτηση", calcTitle:"Υπολογιστής", calcSub:"Δείτε πόσο μπορείτε να κερδίσετε", billLabel:"Μηνιαίος λογαριασμός", currency:"Νόμισμα", calculate:"Υπολογισμός", annualSave:"Ετήσια Εξοικονόμηση", kwh:"kWh / Έτος", panels:"Πάνελ", payback:"Έτη Απόσβεσης", cta:"Λάβετε Προσφορά" },
  blog: { label:"Blog", title1:"Άρθρα και", titleEm:"συμβουλές", subtitle:"Διαβάστε άρθρα μας για ανακαινίσεις και τάσεις.", read:"Διαβάστε", empty:"Δεν υπάρχουν άρθρα ακόμα." },
  testimonials: { label:"Οι Πελάτες μας", title1:"Τι λένε οι", titleEm:"πελάτες", subtitle:"Κριτικές από πραγματικούς πελάτες.", empty:"Σύντομα..." },
  consultation: { label:"Δωρεάν Συμβουλευτική", title1:"Κλείστε", titleEm:"συνάντηση", subtitle:"Δωρεάν συμβουλευτική — επί τόπου ή στην έκθεση.", name:"Όνομα", phone:"Τηλέφωνο", date:"Προτιμώμενη ημερομηνία", message:"Μήνυμα", book:"Κράτηση", success:"Η κράτηση στάλθηκε!" },
  contact: { label:"Επικοινωνία", title1:"Έτοιμοι να ξεκινήσετε", titleEm:"το έργο σας;", subtitle:"ΔΩΡΕΑΝ συμβουλευτική — επικοινωνήστε σήμερα.", address:"Rruga 31 Gushti, Belsh", hours:"Δευ – Σαβ, 07:00 – 18:00", name:"Όνομα", email:"Email", phone:"Τηλέφωνο", message:"Μήνυμα", send:"Αποστολή", info:"Πληροφορίες", whatsapp:"WhatsApp", directions:"Οδηγίες", success:"Το μήνυμα στάλθηκε!" },
  faq: { label:"FAQ", title1:"Συχνές", titleEm:"Ερωτήσεις", q1:"Παραδίδετε εκτός Αλβανίας;", a1:"Ναι, παραδίδουμε σε όλη την Ευρώπη — Κόσοβο, Β. Μακεδονία, Ιταλία, Γερμανία κ.ά.", q2:"Πόσο διαρκεί μια ανακαίνιση;", a2:"Κάθε έργο διαφέρει. Μέσος όρος 3-6 εβδομάδες.", q3:"Είναι όντως δωρεάν η συμβουλευτική;", a3:"Ναι, η πρώτη συμβουλευτική και το 3D σχέδιο είναι εντελώς δωρεάν.", q4:"Με ποιες μάρκες δουλεύετε;", a4:"Δουλεύουμε με τις καλύτερες ευρωπαϊκές μάρκες." },
  footer: { tagline:"Γιατί κάθε σπίτι αξίζει να μοιάζει με όνειρο.", services:"Υπηρεσίες", company:"Εταιρεία", contactCol:"Επικοινωνία", about:"Σχετικά", projects:"Έργα", admin:"Admin", rights:"Όλα τα δικαιώματα κατοχυρωμένα." },
  admin: { login:"Σύνδεση", loginTitle:"Πίνακας Διαχείρισης", email:"Email", password:"Κωδικός", back:"Πίσω", err:"Λάθος email ή κωδικός.", logout:"Αποσύνδεση", role:"admin", today:"Σήμερα", dashboard:"Dashboard", quotes:"Αιτήματα Προσφοράς", transforms:"Μεταμορφώσεις", products:"Προϊόντα", blog:"Blog", projects:"Έργα", solar:"Ρύθμιση Solar", testimonials:"Κριτικές", consultations:"Συμβουλευτικές", settings:"Ρυθμίσεις", search:"Αναζήτηση...", export:"Εξαγωγή CSV", add:"Προσθήκη", edit:"Επεξεργασία", delete:"Διαγραφή", save:"Αποθήκευση", cancel:"Ακύρωση", confirm:"Επιβεβαίωση", confirmDelete:"Σίγουρα διαγραφή;", date:"Ημερομηνία", name:"Όνομα", phone:"Τηλέφωνο", message:"Μήνυμα", status:"Κατάσταση", actions:"Ενέργειες", empty:"Καμία εγγραφή.", saved:"Αποθηκεύτηκε!", deleted:"Διαγράφηκε!", statusNew:"Νέο", statusProgress:"Σε Εξέλιξη", statusDone:"Ολοκληρώθηκε", statusSent:"Πρόταση Στάλθηκε", statusConfirmed:"Επιβεβαιωμένο", statusCancelled:"Ακυρώθηκε", title:"Τίτλος", category:"Κατηγορία", description:"Περιγραφή", brand:"Μάρκα", image:"Εικόνα", featured:"Προτεινόμενο", published:"Δημοσιευμένο", draft:"Πρόχειρο", stars:"Αστέρια", review:"Κριτική", location:"Τοποθεσία", duration:"Διάρκεια", before:"Φωτό Πριν", after:"Φωτό Μετά", company:"Εταιρεία", logo:"Logo", lastUpdated:"Ενημερώθηκε", reset:"Επαναφορά" }
};

// Turkish
const tr = {
  nav: { home:"Ana Sayfa", services:"Hizmetler", showroom:"Showroom", products:"Ürünler", solar:"Solar", blog:"Blog", contact:"İletişim", cta:"Teklif Al" },
  hero: { badge:"1990'dan beri", title:"Çünkü her ev", titleEm:"rüya gibi görünmeyi hak eder", subtitle:"Banyo yenileme, güneş paneli ve kaliteli ürün satışında 36 yıllık tecrübe.", cta1:"Showroom'u Gör", cta2:"İletişime Geç", stat1:"Yıl Tecrübe", stat2:"Proje", stat3:"Tüm Avrupa" },
  services: { label:"Hizmetlerimiz", title1:"Ne", titleEm:"sunuyoruz", subtitle:"Eviniz için eksiksiz çözümler.", s1t:"Banyo Yenileme", s1d:"Tasarımdan montaja kadar tam yenileme.", s2t:"Ücretsiz Danışmanlık", s2d:"Ücretsiz danışmanlık ve 3D proje.", s3t:"Güneş Panelleri", s3d:"Ev, işyeri ve tarım arazisi için kurulum.", s4t:"Ürün Satışı", s4d:"Avrupa'ya teslimatlı fayans, sıhhi tesisat, mobilya.", link:"Daha fazla" },
  showroom: { label:"Showroom", title1:"Showroom'umuzu ziyaret edin:", titleEm:"Belsh", subtitle:"50+ döşeli ortamla sergi.", cta:"Bizi Ziyaret Edin" },
  products: { label:"Ürünler", title1:"Kategoriye göre", titleEm:"göz at", subtitle:"Geniş kaliteli ürün yelpazesi.", c1:"Fayans", c1d:"Yer & Duvar", c2:"Sıhhi Tesisat", c2d:"Bataryalar & Duşlar", c3:"Banyo Mobilyası", c3d:"Lavabo & Aynalar", c4:"Aydınlatma", c4d:"LED & Dekoratif", c5:"Mutfak", c5d:"Evyeler & Aksesuarlar", c6:"Aksesuarlar", c6d:"Tutucular & Detaylar", viewAll:"Tümünü Gör", filter:"Filtrele:", filterAll:"Tümü", filterBath:"Banyo", filterKitchen:"Mutfak", filterLiving:"Oturma Odası", newBadge:"Yeni" },
  transform: { label:"Banyonuzu Dönüştürün", title1:"Fotoğraf gönderin, gerçeğe", titleEm:"dönüştürelim", subtitle:"5 fotoğrafa kadar yükleyin ve vizyonunuzu anlatın.", name:"Tam İsim", phone:"Telefon", email:"E-posta (opsiyonel)", vision:"Vizyonunuzu açıklayın", upload:"Fotoğraf yüklemek için tıklayın", uploadHint:"5 fotoğrafa kadar · JPG, PNG, WEBP", send:"Gönder", beforeAfter:"Öncesi & Sonrası", baDesc:"Mekanları nasıl dönüştürdüğümüzü görün", count:"fotoğraf yüklendi", thanks:"Teşekkürler!", thanksMsg:"Talebiniz alındı. 24 saat içinde dönüş yapacağız.", errReq:"Zorunlu alanları doldurun.", errMax:"Maksimum 5 fotoğraf.", errType:"Yalnızca görsel (JPG, PNG, WEBP)." },
  solar: { label:"Güneş Enerjisi", title1:"Daha iyi bir gelecek için", titleEm:"güneş panelleri", desc:"Dervishi Group eksiksiz güneş paneli kurulumu sunar. Faturanızdan %80'e kadar tasarruf.", f1:"Konut", f1d:"Ev ve daireler için", f2:"Ticari", f2d:"İşletme ve oteller için", f3:"Tarımsal", f3d:"Arazi ve çiftlikler için", f4:"Tam Kurulum", f4d:"Projeden montaja", calcTitle:"Solar Hesaplayıcı", calcSub:"Ne kadar tasarruf edebileceğinizi keşfedin", billLabel:"Aylık elektrik faturası", currency:"Para Birimi", calculate:"Tasarrufu Hesapla", annualSave:"Yıllık Tasarruf", kwh:"kWh / Yıl", panels:"Panel", payback:"Geri Ödeme Yılı", cta:"Solar Teklif Al" },
  blog: { label:"Blog", title1:"Makaleler ve", titleEm:"ipuçları", subtitle:"Yenileme ve trendler hakkında makaleler.", read:"Devamını Oku", empty:"Henüz makale yok." },
  testimonials: { label:"Müşterilerimiz", title1:"Müşteriler ne", titleEm:"diyor", subtitle:"Gerçek müşteri yorumları.", empty:"Yakında..." },
  consultation: { label:"Ücretsiz Danışmanlık", title1:"Bir", titleEm:"randevu alın", subtitle:"Ücretsiz danışmanlık — yerinde veya showroom.", name:"İsim", phone:"Telefon", date:"Tercih edilen tarih", message:"Mesaj", book:"Rezerve Et", success:"Rezervasyon gönderildi!" },
  contact: { label:"Bize Ulaşın", title1:"Projenize başlamaya", titleEm:"hazır mısınız?", subtitle:"ÜCRETSİZ danışmanlık — bugün arayın.", address:"Rruga 31 Gushti, Belsh", hours:"Pzt – Cmt, 07:00 – 18:00", name:"İsim", email:"E-posta", phone:"Telefon", message:"Mesaj", send:"Mesaj Gönder", info:"Bilgi", whatsapp:"WhatsApp", directions:"Yol Tarifi", success:"Mesaj gönderildi!" },
  faq: { label:"SSS", title1:"Sıkça Sorulan", titleEm:"Sorular", q1:"Arnavutluk dışına teslimat var mı?", a1:"Evet, tüm Avrupa'ya teslimat — Kosova, Kuzey Makedonya, İtalya, Almanya vb.", q2:"Banyo yenileme ne kadar sürer?", a2:"Her proje farklıdır. Ortalama 3-6 hafta.", q3:"Danışmanlık gerçekten ücretsiz mi?", a3:"Evet, ilk danışmanlık ve 3D proje tamamen ücretsiz.", q4:"Hangi markalarla çalışıyorsunuz?", a4:"En iyi Avrupa markalarıyla çalışıyoruz." },
  footer: { tagline:"Çünkü her ev rüya gibi görünmeyi hak eder.", services:"Hizmetler", company:"Şirket", contactCol:"İletişim", about:"Hakkımızda", projects:"Projeler", admin:"Admin", rights:"Tüm hakları saklıdır." },
  admin: { login:"Giriş", loginTitle:"Yönetim Paneli", email:"E-posta", password:"Şifre", back:"Siteye Dön", err:"Yanlış e-posta veya şifre.", logout:"Çıkış", role:"admin", today:"Bugün", dashboard:"Panel", quotes:"Teklif Talepleri", transforms:"Dönüşümler", products:"Ürünler", blog:"Blog", projects:"Projeler", solar:"Solar Ayarları", testimonials:"Yorumlar", consultations:"Danışmanlıklar", settings:"Ayarlar", search:"Ara...", export:"CSV Dışa Aktar", add:"Ekle", edit:"Düzenle", delete:"Sil", save:"Kaydet", cancel:"İptal", confirm:"Onayla", confirmDelete:"Silmek istediğinize emin misiniz?", date:"Tarih", name:"İsim", phone:"Telefon", message:"Mesaj", status:"Durum", actions:"İşlemler", empty:"Veri yok.", saved:"Kaydedildi!", deleted:"Silindi!", statusNew:"Yeni", statusProgress:"İşlemde", statusDone:"Tamamlandı", statusSent:"Teklif Gönderildi", statusConfirmed:"Onaylandı", statusCancelled:"İptal Edildi", title:"Başlık", category:"Kategori", description:"Açıklama", brand:"Marka", image:"Görsel", featured:"Öne Çıkan", published:"Yayında", draft:"Taslak", stars:"Yıldız", review:"Yorum", location:"Konum", duration:"Süre", before:"Öncesi", after:"Sonrası", company:"Şirket", logo:"Logo", lastUpdated:"Güncelleme", reset:"Sıfırla" }
};

// French
const fr = {
  nav: { home:"Accueil", services:"Services", showroom:"Showroom", products:"Produits", solar:"Solaire", blog:"Blog", contact:"Contact", cta:"Devis" },
  hero: { badge:"Depuis 1990", title:"Parce que chaque maison", titleEm:"mérite de ressembler à un rêve", subtitle:"36 ans d'expérience en rénovation de salle de bain, panneaux solaires et vente de produits.", cta1:"Voir le Showroom", cta2:"Nous Contacter", stat1:"Ans d'expérience", stat2:"Projets", stat3:"Toute l'Europe" },
  services: { label:"Nos Services", title1:"Ce que nous", titleEm:"offrons", subtitle:"Solutions complètes pour votre maison.", s1t:"Rénovation Salle de Bain", s1d:"Rénovation complète du projet à la pose.", s2t:"Consultation Gratuite", s2d:"Consultation gratuite et projet 3D.", s3t:"Panneaux Solaires", s3d:"Installation pour maisons, entreprises, terres agricoles.", s4t:"Vente de Produits", s4d:"Carrelage, sanitaires, meubles avec livraison en Europe.", link:"En savoir plus" },
  showroom: { label:"Showroom", title1:"Visitez notre showroom à", titleEm:"Belsh", subtitle:"Exposition de plus de 50 environnements meublés.", cta:"Visitez-nous" },
  products: { label:"Produits", title1:"Parcourir par", titleEm:"catégorie", subtitle:"Large gamme de produits de qualité.", c1:"Carrelage", c1d:"Sol & Mur", c2:"Sanitaires", c2d:"Robinets & Douches", c3:"Meubles SDB", c3d:"Vasques & Miroirs", c4:"Éclairage", c4d:"LED & Décoratif", c5:"Cuisine", c5d:"Éviers & Accessoires", c6:"Accessoires", c6d:"Supports & Détails", viewAll:"Tout Voir", filter:"Filtre:", filterAll:"Tous", filterBath:"Salle de bain", filterKitchen:"Cuisine", filterLiving:"Salon", newBadge:"Nouveau" },
  transform: { label:"Transformez votre SDB", title1:"Envoyez la photo, on en fait", titleEm:"une réalité", subtitle:"Téléchargez jusqu'à 5 photos et décrivez votre vision.", name:"Nom complet", phone:"Téléphone", email:"Email (optionnel)", vision:"Décrivez votre vision", upload:"Cliquez pour télécharger", uploadHint:"Jusqu'à 5 photos · JPG, PNG, WEBP", send:"Envoyer", beforeAfter:"Avant & Après", baDesc:"Voyez nos transformations", count:"photos téléchargées", thanks:"Merci!", thanksMsg:"Demande reçue. Réponse sous 24h.", errReq:"Remplissez les champs obligatoires.", errMax:"Maximum 5 photos.", errType:"Images uniquement (JPG, PNG, WEBP)." },
  solar: { label:"Énergie Solaire", title1:"Panneaux solaires pour un", titleEm:"meilleur avenir", desc:"Dervishi Group propose une installation complète de panneaux solaires. Économisez jusqu'à 80%.", f1:"Résidentiel", f1d:"Pour maisons & appartements", f2:"Commercial", f2d:"Pour entreprises & hôtels", f3:"Agricole", f3d:"Pour terres & fermes", f4:"Installation Complète", f4d:"Du projet à la pose", calcTitle:"Calculateur Solaire", calcSub:"Découvrez vos économies", billLabel:"Facture mensuelle", currency:"Devise", calculate:"Calculer", annualSave:"Économies annuelles", kwh:"kWh / An", panels:"Panneaux", payback:"Années d'amortissement", cta:"Demander un Devis" },
  blog: { label:"Blog", title1:"Articles et", titleEm:"conseils", subtitle:"Lisez nos articles sur les rénovations.", read:"Lire", empty:"Aucun article publié." },
  testimonials: { label:"Nos Clients", title1:"Ce que disent nos", titleEm:"clients", subtitle:"Avis de clients réels.", empty:"Bientôt..." },
  consultation: { label:"Consultation Gratuite", title1:"Réservez une", titleEm:"consultation", subtitle:"Consultation gratuite — sur place ou en showroom.", name:"Nom", phone:"Téléphone", date:"Date préférée", message:"Message", book:"Réserver", success:"Réservation envoyée!" },
  contact: { label:"Contactez-nous", title1:"Prêt à démarrer", titleEm:"votre projet?", subtitle:"Consultation GRATUITE — contactez-nous.", address:"Rruga 31 Gushti, Belsh", hours:"Lun – Sam, 07:00 – 18:00", name:"Nom", email:"Email", phone:"Téléphone", message:"Message", send:"Envoyer", info:"Information", whatsapp:"WhatsApp", directions:"Itinéraire", success:"Message envoyé!" },
  faq: { label:"FAQ", title1:"Questions", titleEm:"fréquentes", q1:"Livrez-vous hors d'Albanie?", a1:"Oui, livraison dans toute l'Europe — Kosovo, Macédoine, Italie, Allemagne etc.", q2:"Combien de temps pour une rénovation?", a2:"Chaque projet diffère. Moyenne 3-6 semaines.", q3:"La consultation est-elle vraiment gratuite?", a3:"Oui, première consultation et projet 3D entièrement gratuits.", q4:"Quelles marques utilisez-vous?", a4:"Nous travaillons avec les meilleures marques européennes." },
  footer: { tagline:"Parce que chaque maison mérite de ressembler à un rêve.", services:"Services", company:"Société", contactCol:"Contact", about:"À propos", projects:"Projets", admin:"Admin", rights:"Tous droits réservés." },
  admin: { login:"Connexion", loginTitle:"Panneau Admin", email:"Email", password:"Mot de passe", back:"Retour", err:"Email ou mot de passe incorrect.", logout:"Déconnexion", role:"admin", today:"Aujourd'hui", dashboard:"Tableau de bord", quotes:"Demandes de Devis", transforms:"Transformations", products:"Produits", blog:"Blog", projects:"Projets", solar:"Config. Solaire", testimonials:"Témoignages", consultations:"Consultations", settings:"Paramètres", search:"Rechercher...", export:"Exporter CSV", add:"Ajouter", edit:"Modifier", delete:"Supprimer", save:"Enregistrer", cancel:"Annuler", confirm:"Confirmer", confirmDelete:"Êtes-vous sûr de supprimer?", date:"Date", name:"Nom", phone:"Téléphone", message:"Message", status:"Statut", actions:"Actions", empty:"Aucune donnée.", saved:"Enregistré!", deleted:"Supprimé!", statusNew:"Nouveau", statusProgress:"En cours", statusDone:"Terminé", statusSent:"Proposition envoyée", statusConfirmed:"Confirmé", statusCancelled:"Annulé", title:"Titre", category:"Catégorie", description:"Description", brand:"Marque", image:"Image", featured:"En vedette", published:"Publié", draft:"Brouillon", stars:"Étoiles", review:"Avis", location:"Lieu", duration:"Durée", before:"Photo Avant", after:"Photo Après", company:"Entreprise", logo:"Logo", lastUpdated:"Mis à jour", reset:"Réinitialiser" }
};

const TRANSLATIONS = { sq, en, it, de, el, tr, fr };

const detectLang = () => {
  if (typeof window === "undefined") return "sq";
  const stored = localStorage.getItem("dg_lang");
  if (stored && TRANSLATIONS[stored]) return stored;
  const browser = (navigator.language || "sq").slice(0, 2).toLowerCase();
  return TRANSLATIONS[browser] ? browser : "sq";
};

export function useI18n() {
  const [lang, setLangState] = useState(detectLang);

  useEffect(() => { localStorage.setItem("dg_lang", lang); document.documentElement.lang = lang; }, [lang]);

  const setLang = useCallback((code) => {
    if (TRANSLATIONS[code]) setLangState(code);
  }, []);

  return { t: TRANSLATIONS[lang] || TRANSLATIONS.sq, lang, setLang };
}